version: '3.1'

volumes:
  psql_data:
    driver: local

services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'

  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - 'psql_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: 'postgres'

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - db
    ports:
      - '8093:8080'
    environment:
      ADMINER_PLUGINS: tables-filter tinymce