CREATE TABLE IF NOT EXISTS validators (
	validator_pubkey    VARCHAR(98) NOT NULL PRIMARY KEY,
    status              INTEGER NOT NULL,
    report_count        INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS builder_block_submissions (
	id                        VARCHAR(32) PRIMARY KEY,
    inserted_at               TIMESTAMP NOT NULL default current_timestamp,
    slot                      BIGINT NOT NULL,
    builder_pubkey            TEXT NOT NULL,
    builder_signature         TEXT NOT NULL,
	block_hash                TEXT NOT NULL,
	rpbs				      TEXT NOT NULL,
	rpbs_public_key			  TEXT NOT NULL,
    transaction_byte          TEXT NOT NULL,
	bid_value                 TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_builder_builder_block_submissions ON builder_block_submissions(builder_pubkey);
CREATE INDEX IF NOT EXISTS idx_slot_builder_block_submissions ON builder_block_submissions(slot);
CREATE INDEX IF NOT EXISTS idx_builder_slot_builder_block_submissions ON builder_block_submissions(builder_pubkey, slot);

CREATE TABLE IF NOT EXISTS validator_payloads_delivered (
	id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inserted_at           TIMESTAMP NOT NULL default current_timestamp,
    slot                  BIGINT NOT NULL,
	proposer_pubkey       TEXT NOT NULL,
    block_hash            TEXT NOT NULL,
    payload 	          json NOT NULL
   
);
CREATE INDEX IF NOT EXISTS idx_slot_validator_payloads_delivered ON validator_payloads_delivered(slot, proposer_pubkey);

CREATE TABLE IF NOT EXISTS validator_returned_blocks (
	id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	inserted_at 	    TIMESTAMP NOT NULL DEFAULT current_timestamp,
	signature           TEXT NOT NULL,
	block_hash 		    TEXT NOT NULL,
	proposer_pubkey     TEXT NOT NULL,
	slot        	    BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_slot_validator_returned_blocks ON validator_returned_blocks(slot);

CREATE TABLE IF NOT EXISTS validator_header_delivered (
	id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	inserted_at                 TIMESTAMP NOT NULL default current_timestamp,
    slot                        BIGINT NOT NULL,
	proposer_pubkey             TEXT NOT NULL,
    block_hash                  TEXT NOT NULL,
	bid_value                   DECIMAL(20,0)
);
CREATE INDEX IF NOT EXISTS idx_slot_validator_header_delivered ON validator_header_delivered(slot);
CREATE INDEX IF NOT EXISTS idx_slot_validator_header_delivered ON validator_header_delivered(proposer_pubkey);

CREATE TABLE IF NOT EXISTS validators(
	validator_pubkey      VARCHAR(98) NOT NULL PRIMARY KEY,
	status    	        INTEGER NOT NULL,
	report_count    	        INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS block_builders(
	builder_pubkey      VARCHAR(98) NOT NULL PRIMARY KEY,
	builder_stake 		VARCHAR(200) NOT NULL,
	status    	        BOOLEAN NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_validator_header_delivered ON block_builders(status);

CREATE TABLE IF NOT EXISTS reporters (
  reporter_pubkey     varchar(98) NOT NULL PRIMARY KEY,
  active    	      BOOLEAN NOT NULL,
  report_count        INTEGER NOT NULL
);